export const mockVehicles = [
  {
    id: '1',
    vin: 'ХТТ316380Е1025583',
    vehicle_brand: 'UAZ PATRIOT',
    type: 'Легковой',
    vehicle_type: 'легковой',
    driver_full_name: '02100035',
    state_number: 'Р735АР 11rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '2',
    vin: 'X96275270D0765835',
    vehicle_brand: 'ГАЗ-27527',
    type: 'Легковой',
    vehicle_type: 'грузовой',
    driver_full_name: '02100036',
    state_number: 'О997ТА 11rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: 'КС-3',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '3',
    vin: 'JTEHC05J204046025',
    vehicle_brand: 'TOYOTA LAND CRUISER 100',
    type: 'Легковой',
    vehicle_type: 'легковой',
    driver_full_name: '02100037',
    state_number: 'В001ОЕ 11rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'не исправен',
    current_location: 'ОП "Самоцветгый"',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '4',
    vin: 'MR0FR22G800758899',
    vehicle_brand: 'TOYOTA HILUX',
    type: 'Легковой',
    vehicle_type: 'грузовой-бортовой',
    driver_full_name: '02100038',
    state_number: 'О622ТС 11rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '5',
    vin: 'JТМНТ05J104036591',
    vehicle_brand: 'TOYOTA LAND CRUISER 200',
    type: 'Легковой',
    vehicle_type: 'легковой',
    driver_full_name: '02100039',
    state_number: 'В001КХ 11rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '6',
    vin: 'XU6298940G0000485',
    vehicle_brand: '29894',
    type: 'Легковой',
    vehicle_type: 'легковой',
    driver_full_name: '02100040',
    state_number: 'Р407ВН 11rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '7',
    vin: 'XU6298940G0000473',
    vehicle_brand: '29894',
    type: 'Легковой',
    vehicle_type: 'легковой',
    driver_full_name: '02100041',
    state_number: 'Р408ВН 11rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '8',
    vin: 'Х96322170Н0820089',
    vehicle_brand: 'ГАЗ-32217',
    type: 'Легковой',
    vehicle_type: 'специализированное пассажирское ТС (8 мест)',
    driver_full_name: '02100042',
    state_number: 'Р442ВН 11rus',
    repair_type: '',
    repair_waiting_time: 'ожидает ремонта',
    downtime_duration: '',
    technical_condition: 'не исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '9',
    vin: 'ХU6298930J1001128',
    vehicle_brand: '29893',
    type: 'Легковой',
    vehicle_type: 'грузовой фургон',
    driver_full_name: '02100043',
    state_number: 'Р623МН 11rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '10',
    vin: 'XU629894МК1001265',
    vehicle_brand: '29894',
    type: 'Легковой',
    vehicle_type: 'легковой',
    driver_full_name: '02100044',
    state_number: 'Р916МС 11rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '11',
    vin: 'XU629894ML1001427',
    vehicle_brand: '29894',
    type: 'Легковой',
    vehicle_type: 'легковой',
    driver_full_name: '02100045',
    state_number: 'Р968НК 11rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '12',
    vin: 'ХТС431183С2434744',
    vehicle_brand: 'КАМАЗ-43118-24',
    type: 'Грузовые',
    vehicle_type: 'бортовой',
    driver_full_name: '02100046',
    state_number: 'О823ТС 11rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '13',
    vin: 'ХТС431183С2423401',
    vehicle_brand: 'КАМАЗ-43118-24',
    type: 'Грузовые',
    vehicle_type: 'бортовой с КМУ',
    driver_full_name: '02100047',
    state_number: 'О137РК 11rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '14',
    vin: 'X96330263F2604321',
    vehicle_brand: 'ГАЗ-330263',
    type: 'Грузовые',
    vehicle_type: 'грузовой бортовой',
    driver_full_name: '02100048',
    state_number: 'Р521АВ 11rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '15',
    vin: 'Х96330263G2635721',
    vehicle_brand: 'ГАЗ-330263',
    type: 'Грузовые',
    vehicle_type: 'грузовой бортовой',
    driver_full_name: '02100049',
    state_number: 'Р970АР 11rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '16',
    vin: 'Х96270570G0800044',
    vehicle_brand: 'ГАЗ-27057',
    type: 'Грузовые',
    vehicle_type: 'грузовой фургон',
    driver_full_name: '02100050',
    state_number: 'Р968АР 11rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '17',
    vin: 'XE26589A6F0000201',
    vehicle_brand: '658901-05',
    type: 'Грузовые',
    vehicle_type: 'автомобиль самосвал',
    driver_full_name: '02100051',
    state_number: 'Р972АС 11rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '18',
    vin: 'Z9L780722F0000011',
    vehicle_brand: '780722',
    type: 'Грузовые',
    vehicle_type: 'автомобиль бортовой',
    driver_full_name: '02100052',
    state_number: 'Р965АС 11rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '19',
    vin: 'Z9L780722F0000010',
    vehicle_brand: '780722',
    type: 'Грузовые',
    vehicle_type: 'автомобиль бортовой',
    driver_full_name: '02100053',
    state_number: 'Р989АС 11rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '20',
    vin: 'X89393005F0AY7015',
    vehicle_brand: '393005',
    type: 'Грузовые',
    vehicle_type: 'автомобиль бортовой',
    driver_full_name: '02100054',
    state_number: 'Р932АС 11rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '21',
    vin: 'XTC430805L1430402',
    vehicle_brand: 'КАМАЗ 4308-N5',
    type: 'Грузовые',
    vehicle_type: 'грузовой бортовой',
    driver_full_name: '02100055',
    state_number: 'Р425РН 11rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '22',
    vin: 'X1M32032MH0001614',
    vehicle_brand: 'ПАЗ-320302-11',
    type: 'Автобусы',
    vehicle_type: 'автобусы прочие',
    driver_full_name: '02100056',
    state_number: 'Р631ЕН 11rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '23',
    vin: 'Х96322120F0783813',
    vehicle_brand: 'ГАЗ-32212',
    type: 'Автобусы',
    vehicle_type: 'автобусы прочие',
    driver_full_name: '02100057',
    state_number: 'Р503АВ 11rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '24',
    vin: 'X1F4208GEE0000055',
    vehicle_brand: 'НЕФАЗ-4208-41',
    type: 'Автобусы',
    vehicle_type: 'автобусы прочие',
    driver_full_name: '02100058',
    state_number: 'Р520АВ 11rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '25',
    vin: 'Х1М32042ЕВ0001099',
    vehicle_brand: 'ПАЗ-320402-05',
    type: 'Автобусы',
    vehicle_type: 'автобусы прочие',
    driver_full_name: '02100059',
    state_number: 'О763ЕС 11rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '26',
    vin: 'LXG0PA484PA009519',
    vehicle_brand: 'XCMG XCA100 S',
    type: 'Автокраны',
    vehicle_type: 'автокран',
    driver_full_name: '02100060',
    state_number: 'Р212ХА 11rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '27',
    vin: 'отсутствует',
    vehicle_brand: 'АС-265ТТ (Демаг)',
    type: 'Автокраны',
    vehicle_type: 'автокран',
    driver_full_name: '02100061',
    state_number: 'В096МР 11rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '28',
    vin: 'Z8C557133D0000097',
    vehicle_brand: 'КС-55713-3 на шасси УРАЛ 4320-1951-70',
    type: 'Автокраны',
    vehicle_type: 'кран автомобильный',
    driver_full_name: '02100062',
    state_number: 'О390УЕ 11rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '29',
    vin: 'X89557135G4AH5390',
    vehicle_brand: 'КС-55713-5К-1 на шасси КАМАЗ 43118-32',
    type: 'Автокраны',
    vehicle_type: 'кран автомобильный',
    driver_full_name: '02100063',
    state_number: 'Р312ВХ 11rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '30',
    vin: 'X89557135G4AH5392',
    vehicle_brand: 'КС-55713-5К-1 на шасси КАМАЗ 43118-32',
    type: 'Автокраны',
    vehicle_type: 'кран автомобильный',
    driver_full_name: '02100064',
    state_number: 'Р318ВХ 11rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '31',
    vin: 'XDF658618G0002177',
    vehicle_brand: 'КАМАЗ 658618',
    type: 'Автокраны',
    vehicle_type: 'автогидроподьемник',
    driver_full_name: '02100065',
    state_number: 'Р320ВХ 11rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '32',
    vin: 'Х895662ВВ90АJ2103',
    vehicle_brand: '5662ВВ АЦ-6.0-40 (5557)',
    type: 'Пожарные',
    vehicle_type: 'автоцистерна пожарная',
    driver_full_name: '02100066',
    state_number: 'Н409ТН 11rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '33',
    vin: 'Х895662ВВ60АJ2107',
    vehicle_brand: '5662ВВ АЦ 6.0-40',
    type: 'Пожарные',
    vehicle_type: 'автомобиль пожарный',
    driver_full_name: '02100067',
    state_number: 'В019МР 11rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '34',
    vin: 'X895662CLDAAJ2014',
    vehicle_brand: '5662CL АЦ 6,0-40 (5557)',
    type: 'Пожарные',
    vehicle_type: 'цистерна пожарная',
    driver_full_name: '02100068',
    state_number: 'О824ТС 11rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '35',
    vin: 'TNT230N9TCK046415',
    vehicle_brand: 'TATRA T815-230N9T',
    type: 'Тягачи',
    vehicle_type: 'грузовой тягач седельный',
    driver_full_name: '02100069',
    state_number: 'О802УО 11rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '36',
    vin: 'ХТС651164F1330490',
    vehicle_brand: 'КАМАЗ 65116-30',
    type: 'Тягачи',
    vehicle_type: 'тягач седельный',
    driver_full_name: '02100070',
    state_number: 'Р977АС 11rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '37',
    vin: 'Х0Р442644GG000006',
    vehicle_brand: '442644Г на шасси КАМАЗ 43118-32',
    type: 'Тягачи',
    vehicle_type: 'тягач специальный',
    driver_full_name: '02100071',
    state_number: 'Р314ВХ 11rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '38',
    vin: 'ХТС65225YС1282578',
    vehicle_brand: 'КАМАЗ 65225-22',
    type: 'Тягачи',
    vehicle_type: 'тягач седельный',
    driver_full_name: '02100072',
    state_number: 'О473УЕ 11rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '39',
    vin: 'Х1Р637040К0000844',
    vehicle_brand: 'УРАЛ 63704-3951',
    type: 'Тягачи',
    vehicle_type: 'седельный тягач',
    driver_full_name: '02100073',
    state_number: 'Р836МН 11rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '40',
    vin: 'отсутствует',
    vehicle_brand: 'ЗИЛ-131',
    type: 'Спец. Машин.',
    vehicle_type: 'спец. автомобиль',
    driver_full_name: '02100074',
    state_number: 'В010ВО 11rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '41',
    vin: 'XU557514490000069',
    vehicle_brand: 'КАМАЗ 575144',
    type: 'Спец. Машин.',
    vehicle_type: 'автомаст. сварочная',
    driver_full_name: '02100075',
    state_number: 'Н055ТТ 11rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '42',
    vin: 'XU557514490000077',
    vehicle_brand: 'КАМАЗ 575144',
    type: 'Спец. Машин.',
    vehicle_type: 'лаборатория АСУиТМ',
    driver_full_name: '02100076',
    state_number: 'Н026ТТ 11rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '43',
    vin: 'Х8958082090DM7002',
    vehicle_brand: 'УМП 4326 (5808-0000020)',
    type: 'Спец. Машин.',
    vehicle_type: 'универсальный моторный подогреватель - УМП',
    driver_full_name: '02100077',
    state_number: 'Н426ТН 11rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '44',
    vin: 'X89675624P0GN0005',
    vehicle_brand: 'без марки',
    type: 'Спец. Машин.',
    vehicle_type: 'лаборатория передвижная',
    driver_full_name: '02100078',
    state_number: 'Р 570 УА 11rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '45',
    vin: 'X897098Z1N0FZ6010',
    vehicle_brand: 'без марки',
    type: 'Спец. Машин.',
    vehicle_type: 'передвижная парогенераторная установка',
    driver_full_name: '02100079',
    state_number: 'Р 578 УА 11rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '46',
    vin: 'Х8948672LE0BE6022',
    vehicle_brand: 'КАМАЗ 43118-46 4867',
    type: 'Спец. Машин.',
    vehicle_type: 'автомобиль-мастерск.',
    driver_full_name: '02100080',
    state_number: 'Р961АР 11rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '47',
    vin: 'X89579514FEEX6061',
    vehicle_brand: '579514E',
    type: 'Спец. Машин.',
    vehicle_type: 'мастерская парм',
    driver_full_name: '02100081',
    state_number: 'Р966АС 11rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '48',
    vin: 'X894923G2F1DW3011',
    vehicle_brand: '4923G2-01 (УМП-400)',
    type: 'Спец. Машин.',
    vehicle_type: 'фургон с технологическим оборудованием',
    driver_full_name: '02100082',
    state_number: 'Р967АС 11rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '49',
    vin: 'XDF658613F9108009',
    vehicle_brand: '658613 специальный АНРВ',
    type: 'Спец. Машин.',
    vehicle_type: 'а/м специальный АНРВ',
    driver_full_name: '02100083',
    state_number: 'Р968АС 11rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '50',
    vin: 'X89MPZ2AAFCAR4061',
    vehicle_brand: 'MPZ2AA (ЭХЗ)',
    type: 'Спец. Машин.',
    vehicle_type: 'а/м специальный',
    driver_full_name: '02100084',
    state_number: 'Р990АС 11rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '51',
    vin: 'X89MPZ2AAFCAR4060',
    vehicle_brand: 'MPZ2AA (ЭХЗ)',
    type: 'Спец. Машин.',
    vehicle_type: 'а/м специальный',
    driver_full_name: '02100085',
    state_number: 'Р991АС 11rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '52',
    vin: 'XDF658613F9107020',
    vehicle_brand: '658613',
    type: 'Спец. Машин.',
    vehicle_type: 'а/м специальный АРОК',
    driver_full_name: '02100086',
    state_number: 'Р970АС 11rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '53',
    vin: 'Х895675А0D0BJ6946',
    vehicle_brand: '5675AO',
    type: 'Спец. Машин.',
    vehicle_type: 'топливозаправщик',
    driver_full_name: '02100087',
    state_number: 'О810ТЕ 11rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '54',
    vin: 'X89MPZ2ABLWAR4213',
    vehicle_brand: 'МПЗ MPZ2AB  АС  ЛЭС',
    type: 'Спец. Машин.',
    vehicle_type: 'Специализированный прочее',
    driver_full_name: '02100088',
    state_number: 'Р403РН 11rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '55',
    vin: 'X89MPZ2ABLWAR4214',
    vehicle_brand: 'МПЗ MPZ2AB  АС  ЛЭС',
    type: 'Спец. Машин.',
    vehicle_type: 'Специализированный прочее',
    driver_full_name: '02100089',
    state_number: 'Р365РН 11rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '56',
    vin: 'отсутствует',
    vehicle_brand: 'Снегоболотоход ТТМ 3902ПС-01',
    type: 'Снегоболотоход',
    vehicle_type: 'снегоболотоход гусеничный',
    driver_full_name: '02100090',
    state_number: '3113КХ 11rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '57',
    vin: 'отсутствует',
    vehicle_brand: 'Снегоболотоход ТТМ 3902ПС-01',
    type: 'Снегоболотоход',
    vehicle_type: 'снегоболотоход гусеничный',
    driver_full_name: '02100091',
    state_number: '3217КК 11rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '58',
    vin: 'отсутствует',
    vehicle_brand: 'D9N Катерпиллар',
    type: 'Бульдозеры',
    vehicle_type: 'бульдозер',
    driver_full_name: '02100092',
    state_number: '2815КО 11 rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '59',
    vin: 'отсутствует',
    vehicle_brand: 'D9N Катерпиллар',
    type: 'Бульдозеры',
    vehicle_type: 'бульдозер',
    driver_full_name: '02100093',
    state_number: '2813КО 11 rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '60',
    vin: 'отсутствует',
    vehicle_brand: 'D9N КАТ',
    type: 'Бульдозеры',
    vehicle_type: 'бульдозер',
    driver_full_name: '02100094',
    state_number: '2816КО 11 rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '61',
    vin: 'отсутствует',
    vehicle_brand: 'Бульдозер колёсный К-702МБА-01-БКУ',
    type: 'Бульдозеры',
    vehicle_type: 'бульдозер колесный универсальный "Кировец"',
    driver_full_name: '02100095',
    state_number: '9531КВ 11 rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '62',
    vin: 'отсутствует',
    vehicle_brand: 'Бульдозер Б 10 МБ.0122-2В4',
    type: 'Бульдозеры',
    vehicle_type: 'трактор с бульдозерным оборудованием',
    driver_full_name: '02100096',
    state_number: '9530КВ 11 rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '63',
    vin: 'отсутствует',
    vehicle_brand: 'BV-206D6N',
    type: 'Гусеничные тягачи',
    vehicle_type: 'транспортер грузовой',
    driver_full_name: '02100097',
    state_number: '5795КВ 11 rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '64',
    vin: 'отсутствует',
    vehicle_brand: 'HAGGLUND BV-206',
    type: 'Гусеничные тягачи',
    vehicle_type: 'трактор',
    driver_full_name: '02100098',
    state_number: 'КК3234 11rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '65',
    vin: 'отсутствует',
    vehicle_brand: 'Погрузчик фронтальный "Locust L752"',
    type: 'Погрузчики',
    vehicle_type: 'погрузчик фронт.универс.',
    driver_full_name: '02100099',
    state_number: 'КВ7180 11rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '66',
    vin: 'отсутствует',
    vehicle_brand: 'Погрузчик фронтальный "Locust L752"',
    type: 'Погрузчики',
    vehicle_type: 'погрузчик фронтальный',
    driver_full_name: '02100100',
    state_number: 'КК4231 11rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '67',
    vin: 'отсутствует',
    vehicle_brand: 'Автопогрузчик KION BAOLI CPCD30',
    type: 'Погрузчики',
    vehicle_type: 'Автопогрузчик',
    driver_full_name: '02100101',
    state_number: 'КК4681 11rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '68',
    vin: 'отсутствует',
    vehicle_brand: 'АС-81 К-701',
    type: 'Сварочные агрегаты',
    vehicle_type: 'агрегат сварочный',
    driver_full_name: '02100102',
    state_number: '2830КО 11 rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '69',
    vin: 'отсутствует',
    vehicle_brand: 'УПС-100 К-701',
    type: 'Сварочные агрегаты',
    vehicle_type: 'агрегат сварочный',
    driver_full_name: '02100103',
    state_number: '2831КО 11 rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '70',
    vin: 'отсутствует',
    vehicle_brand: 'TRYBERG TWM-180',
    type: 'Сварочные агрегаты',
    vehicle_type: 'сварочный агрегат',
    driver_full_name: '02100104',
    state_number: '8905КУ 11 rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '71',
    vin: 'отсутствует',
    vehicle_brand: 'АС-81 К-700А',
    type: 'Сварочные агрегаты',
    vehicle_type: 'агрегат сварочный',
    driver_full_name: '02100105',
    state_number: '1953КО 11 rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '72',
    vin: 'отсутствует',
    vehicle_brand: 'Д-355-С-3 Камацу',
    type: 'Трубоукладчики',
    vehicle_type: 'трубоукладчик',
    driver_full_name: '02100106',
    state_number: '2719КХ 11 rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '73',
    vin: 'отсутствует',
    vehicle_brand: 'Д-355-С-3 Камацу',
    type: 'Трубоукладчики',
    vehicle_type: 'трубоукладчик',
    driver_full_name: '02100107',
    state_number: '2818КО 11 rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '74',
    vin: 'отсутствует',
    vehicle_brand: 'Д-355-С-3 Камацу',
    type: 'Трубоукладчики',
    vehicle_type: 'трубоукладчик',
    driver_full_name: '02100108',
    state_number: '2820КО 11 rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '75',
    vin: 'отсутствует',
    vehicle_brand: 'Д-355-С-3 Камацу',
    type: 'Трубоукладчики',
    vehicle_type: 'трубоукладчик',
    driver_full_name: '02100109',
    state_number: '1411МТ 11 rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '76',
    vin: 'отсутствует',
    vehicle_brand: 'Д-355-С-3 Камацу',
    type: 'Трубоукладчики',
    vehicle_type: 'трубоукладчик',
    driver_full_name: '02100110',
    state_number: '2821КО 11 rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '77',
    vin: 'отсутствует',
    vehicle_brand: 'Четра ТГ-511Я',
    type: 'Трубоукладчики',
    vehicle_type: 'трубоукладчик',
    driver_full_name: '02100111',
    state_number: '6066МА11 rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '78',
    vin: 'отсутствует',
    vehicle_brand: 'Четра ТГ-511Я',
    type: 'Трубоукладчики',
    vehicle_type: 'трубоукладчик',
    driver_full_name: '02100112',
    state_number: '6069МА 11 rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '79',
    vin: 'отсутствует',
    vehicle_brand: 'Четра ТГ-511Я',
    type: 'Трубоукладчики',
    vehicle_type: 'трубоукладчик',
    driver_full_name: '02100113',
    state_number: '6068МА 11 rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '80',
    vin: 'отсутствует',
    vehicle_brand: 'Четра ТГ-511Я',
    type: 'Трубоукладчики',
    vehicle_type: 'трубоукладчик',
    driver_full_name: '02100114',
    state_number: '6067МА 11 rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '81',
    vin: 'отсутствует',
    vehicle_brand: 'Экскаватор САТ 320DL',
    type: 'Экскаваторы',
    vehicle_type: 'экскаватор',
    driver_full_name: '02100115',
    state_number: 'КВ9589 11rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '82',
    vin: 'отсутствует',
    vehicle_brand: 'Экскаватор САТ 320DL',
    type: 'Экскаваторы',
    vehicle_type: 'экскаватор',
    driver_full_name: '02100116',
    state_number: 'КВ9539 11rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '83',
    vin: 'отсутствует',
    vehicle_brand: 'Экскаватор CAT 336DL',
    type: 'Экскаваторы',
    vehicle_type: 'экскаватор',
    driver_full_name: '02100117',
    state_number: '4507 МА 11 rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '84',
    vin: 'отсутствует',
    vehicle_brand: 'Hyundai, HX220S',
    type: 'Экскаваторы',
    vehicle_type: 'экскаватор',
    driver_full_name: '02100118',
    state_number: '3990МА 11 rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '85',
    vin: 'отсутствует',
    vehicle_brand: 'Kraneks-P240-0124',
    type: 'Экскаваторы',
    vehicle_type: 'экскаватор',
    driver_full_name: '02100119',
    state_number: '6148МА 11rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '86',
    vin: 'отсутствует',
    vehicle_brand: 'КО-812-1',
    type: 'Спец. Техника',
    vehicle_type: 'маш.универсальная уборочная',
    driver_full_name: '02100120',
    state_number: '9509КВ 11 rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  },
  {
    id: '87',
    vin: 'отсутствует',
    vehicle_brand: 'К-702-МВА-УДМ-2',
    type: 'Спец. Техника',
    vehicle_type: 'универсальная дорожная машина',
    driver_full_name: '02100121',
    state_number: '4400КХ 11 rus',
    repair_type: '',
    repair_waiting_time: '',
    downtime_duration: '',
    technical_condition: 'исправен',
    current_location: '',
    company_affiliation: 'Вуктыльское ЛПУМГ'
  }
];

export const mockDepartments = [
  { id: '1', name: 'Транспортный цех', headName: 'Иванов И.И.', email: 'transport@company.ru' },
  { id: '2', name: 'Ремонтная служба', headName: 'Петров П.П.', email: 'repair@company.ru' },
  { id: '3', name: 'Служба эксплуатации', headName: 'Сидоров С.С.', email: 'exploitation@company.ru' },
  { id: '4', name: 'Аварийная служба', headName: 'Козлов К.К.', email: 'emergency@company.ru' },
  { id: '5', name: 'Служба главного инженера', headName: 'Смирнов А.А.', email: 'chief@company.ru' },
  { id: '6', name: 'Служба главного механика', headName: 'Васильев В.В.', email: 'mechanic@company.ru' },
];